version: "3.8"

services:
  web:
    image: ansible/awx:13.0.0
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/bin/launch_awx.sh && /usr/bin/launch_awx.sh"]
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh:ro
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./projects:/var/lib/awx/projects:rw
      - ./inventories:/var/lib/awx/inventories:rw
    environment:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""

  task:
    image: ansible/awx:13.0.0
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh:ro
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py:ro
      - ./projects:/var/lib/awx/projects:rw
      - ./inventories:/var/lib/awx/inventories:rw
    environment:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - awx_redis_data:/data

  postgres:
    image: postgres:10
    command: postgres -c listen_addresses='*'
    volumes:
      - awx_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.5.2
    user: root
    environment:
      - KIBANA_HOST=kibana:5601
      - ELASTIC_HOST=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - AWX_DB_USER=awx
      - AWX_DB_PASS=awxpass
    command: -system.hostfs=/hostfs
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat/dashboards:/usr/share/metricbeat/kibana/7/dashboard:ro
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  awx_redis_data:
  awx_pgdata:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
  elasticsearch_data:
