version: "3.8"

services:

  web:
    image: ansible/awx:13.0.0
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh:ro
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./projects:/var/lib/awx/projects:rw
      - ./inventories:/var/lib/awx/inventories:rw
    environment:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
    deploy:
      restart_policy:
        condition: on-failure

  task:
    image: ansible/awx:13.0.0
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - ./conf/SECRET_KEY.txt:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh:ro
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py:ro
      - ./projects:/var/lib/awx/projects:rw
      - ./inventories:/var/lib/awx/inventories:rw
    environment:
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--unixsocket", ""]
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - awx_redis_data:/data
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:10
    command: postgres -c listen_addresses='*'
    volumes:
      - awx_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: ""
      https_proxy: ""
      no_proxy: ""
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  awx_redis_data:
  awx_pgdata:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
